// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACe0UyTwYrrH9oXcTUELHvxRL7qCt62ow',
    appId: '1:807189474286:android:dd39ff815caf5bd89b7cff',
    messagingSenderId: '807189474286',
    projectId: 'testproject-1d9d9',
    databaseURL: 'https://testproject-1d9d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testproject-1d9d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZr5VpziWRWLTPwo-uqgGYiRsufleG0Fs',
    appId: '1:807189474286:ios:f1abfef85081ac229b7cff',
    messagingSenderId: '807189474286',
    projectId: 'testproject-1d9d9',
    databaseURL: 'https://testproject-1d9d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testproject-1d9d9.appspot.com',
    androidClientId: '807189474286-5henphi6adu0fk7jh4if4pr5poplh7fr.apps.googleusercontent.com',
    iosClientId: '807189474286-6i5fo5ev621n8l42ae49rigge1dsjodq.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFirebase',
  );
}
